// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBMessage.proto

package com.xxim.codec.protobuf;

public final class PBMessage {
  private PBMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface pbmessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbmessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string srcid = 1;</code>
     */
    java.lang.String getSrcid();
    /**
     * <code>string srcid = 1;</code>
     */
    com.google.protobuf.ByteString
        getSrcidBytes();

    /**
     * <code>string dstid = 2;</code>
     */
    java.lang.String getDstid();
    /**
     * <code>string dstid = 2;</code>
     */
    com.google.protobuf.ByteString
        getDstidBytes();

    /**
     * <code>int32 packettype = 3;</code>
     */
    int getPackettype();

    /**
     * <code>int32 bodytype = 4;</code>
     */
    int getBodytype();

    /**
     * <code>int64 srccts = 5;</code>
     */
    long getSrccts();

    /**
     * <code>int64 serverid = 6;</code>
     */
    long getServerid();

    /**
     * <code>string srcdeviceid = 7;</code>
     */
    java.lang.String getSrcdeviceid();
    /**
     * <code>string srcdeviceid = 7;</code>
     */
    com.google.protobuf.ByteString
        getSrcdeviceidBytes();

    /**
     * <code>int32 status = 8;</code>
     */
    int getStatus();

    /**
     * <code>int64 cts = 9;</code>
     */
    long getCts();

    /**
     * <code>string fromname = 10;</code>
     */
    java.lang.String getFromname();
    /**
     * <code>string fromname = 10;</code>
     */
    com.google.protobuf.ByteString
        getFromnameBytes();

    /**
     * <code>bytes body = 11;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code pbmessage}
   */
  public  static final class pbmessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pbmessage)
      pbmessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use pbmessage.newBuilder() to construct.
    private pbmessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private pbmessage() {
      srcid_ = "";
      dstid_ = "";
      packettype_ = 0;
      bodytype_ = 0;
      srccts_ = 0L;
      serverid_ = 0L;
      srcdeviceid_ = "";
      status_ = 0;
      cts_ = 0L;
      fromname_ = "";
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private pbmessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              srcid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              dstid_ = s;
              break;
            }
            case 24: {

              packettype_ = input.readInt32();
              break;
            }
            case 32: {

              bodytype_ = input.readInt32();
              break;
            }
            case 40: {

              srccts_ = input.readInt64();
              break;
            }
            case 48: {

              serverid_ = input.readInt64();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              srcdeviceid_ = s;
              break;
            }
            case 64: {

              status_ = input.readInt32();
              break;
            }
            case 72: {

              cts_ = input.readInt64();
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              fromname_ = s;
              break;
            }
            case 90: {

              body_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xxim.codec.protobuf.PBMessage.internal_static_pbmessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xxim.codec.protobuf.PBMessage.internal_static_pbmessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xxim.codec.protobuf.PBMessage.pbmessage.class, com.xxim.codec.protobuf.PBMessage.pbmessage.Builder.class);
    }

    public static final int SRCID_FIELD_NUMBER = 1;
    private volatile java.lang.Object srcid_;
    /**
     * <code>string srcid = 1;</code>
     */
    public java.lang.String getSrcid() {
      java.lang.Object ref = srcid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        srcid_ = s;
        return s;
      }
    }
    /**
     * <code>string srcid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSrcidBytes() {
      java.lang.Object ref = srcid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        srcid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DSTID_FIELD_NUMBER = 2;
    private volatile java.lang.Object dstid_;
    /**
     * <code>string dstid = 2;</code>
     */
    public java.lang.String getDstid() {
      java.lang.Object ref = dstid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dstid_ = s;
        return s;
      }
    }
    /**
     * <code>string dstid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDstidBytes() {
      java.lang.Object ref = dstid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dstid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PACKETTYPE_FIELD_NUMBER = 3;
    private int packettype_;
    /**
     * <code>int32 packettype = 3;</code>
     */
    public int getPackettype() {
      return packettype_;
    }

    public static final int BODYTYPE_FIELD_NUMBER = 4;
    private int bodytype_;
    /**
     * <code>int32 bodytype = 4;</code>
     */
    public int getBodytype() {
      return bodytype_;
    }

    public static final int SRCCTS_FIELD_NUMBER = 5;
    private long srccts_;
    /**
     * <code>int64 srccts = 5;</code>
     */
    public long getSrccts() {
      return srccts_;
    }

    public static final int SERVERID_FIELD_NUMBER = 6;
    private long serverid_;
    /**
     * <code>int64 serverid = 6;</code>
     */
    public long getServerid() {
      return serverid_;
    }

    public static final int SRCDEVICEID_FIELD_NUMBER = 7;
    private volatile java.lang.Object srcdeviceid_;
    /**
     * <code>string srcdeviceid = 7;</code>
     */
    public java.lang.String getSrcdeviceid() {
      java.lang.Object ref = srcdeviceid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        srcdeviceid_ = s;
        return s;
      }
    }
    /**
     * <code>string srcdeviceid = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSrcdeviceidBytes() {
      java.lang.Object ref = srcdeviceid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        srcdeviceid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 8;
    private int status_;
    /**
     * <code>int32 status = 8;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int CTS_FIELD_NUMBER = 9;
    private long cts_;
    /**
     * <code>int64 cts = 9;</code>
     */
    public long getCts() {
      return cts_;
    }

    public static final int FROMNAME_FIELD_NUMBER = 10;
    private volatile java.lang.Object fromname_;
    /**
     * <code>string fromname = 10;</code>
     */
    public java.lang.String getFromname() {
      java.lang.Object ref = fromname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromname_ = s;
        return s;
      }
    }
    /**
     * <code>string fromname = 10;</code>
     */
    public com.google.protobuf.ByteString
        getFromnameBytes() {
      java.lang.Object ref = fromname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 11;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>bytes body = 11;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSrcidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, srcid_);
      }
      if (!getDstidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dstid_);
      }
      if (packettype_ != 0) {
        output.writeInt32(3, packettype_);
      }
      if (bodytype_ != 0) {
        output.writeInt32(4, bodytype_);
      }
      if (srccts_ != 0L) {
        output.writeInt64(5, srccts_);
      }
      if (serverid_ != 0L) {
        output.writeInt64(6, serverid_);
      }
      if (!getSrcdeviceidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, srcdeviceid_);
      }
      if (status_ != 0) {
        output.writeInt32(8, status_);
      }
      if (cts_ != 0L) {
        output.writeInt64(9, cts_);
      }
      if (!getFromnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, fromname_);
      }
      if (!body_.isEmpty()) {
        output.writeBytes(11, body_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSrcidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, srcid_);
      }
      if (!getDstidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dstid_);
      }
      if (packettype_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, packettype_);
      }
      if (bodytype_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, bodytype_);
      }
      if (srccts_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, srccts_);
      }
      if (serverid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, serverid_);
      }
      if (!getSrcdeviceidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, srcdeviceid_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, status_);
      }
      if (cts_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, cts_);
      }
      if (!getFromnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, fromname_);
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xxim.codec.protobuf.PBMessage.pbmessage)) {
        return super.equals(obj);
      }
      com.xxim.codec.protobuf.PBMessage.pbmessage other = (com.xxim.codec.protobuf.PBMessage.pbmessage) obj;

      boolean result = true;
      result = result && getSrcid()
          .equals(other.getSrcid());
      result = result && getDstid()
          .equals(other.getDstid());
      result = result && (getPackettype()
          == other.getPackettype());
      result = result && (getBodytype()
          == other.getBodytype());
      result = result && (getSrccts()
          == other.getSrccts());
      result = result && (getServerid()
          == other.getServerid());
      result = result && getSrcdeviceid()
          .equals(other.getSrcdeviceid());
      result = result && (getStatus()
          == other.getStatus());
      result = result && (getCts()
          == other.getCts());
      result = result && getFromname()
          .equals(other.getFromname());
      result = result && getBody()
          .equals(other.getBody());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SRCID_FIELD_NUMBER;
      hash = (53 * hash) + getSrcid().hashCode();
      hash = (37 * hash) + DSTID_FIELD_NUMBER;
      hash = (53 * hash) + getDstid().hashCode();
      hash = (37 * hash) + PACKETTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getPackettype();
      hash = (37 * hash) + BODYTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getBodytype();
      hash = (37 * hash) + SRCCTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSrccts());
      hash = (37 * hash) + SERVERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getServerid());
      hash = (37 * hash) + SRCDEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getSrcdeviceid().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + CTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCts());
      hash = (37 * hash) + FROMNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFromname().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xxim.codec.protobuf.PBMessage.pbmessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxim.codec.protobuf.PBMessage.pbmessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxim.codec.protobuf.PBMessage.pbmessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxim.codec.protobuf.PBMessage.pbmessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxim.codec.protobuf.PBMessage.pbmessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxim.codec.protobuf.PBMessage.pbmessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxim.codec.protobuf.PBMessage.pbmessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xxim.codec.protobuf.PBMessage.pbmessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xxim.codec.protobuf.PBMessage.pbmessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xxim.codec.protobuf.PBMessage.pbmessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xxim.codec.protobuf.PBMessage.pbmessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xxim.codec.protobuf.PBMessage.pbmessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xxim.codec.protobuf.PBMessage.pbmessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pbmessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pbmessage)
        com.xxim.codec.protobuf.PBMessage.pbmessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xxim.codec.protobuf.PBMessage.internal_static_pbmessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xxim.codec.protobuf.PBMessage.internal_static_pbmessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xxim.codec.protobuf.PBMessage.pbmessage.class, com.xxim.codec.protobuf.PBMessage.pbmessage.Builder.class);
      }

      // Construct using com.xxim.codec.protobuf.PBMessage.pbmessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        srcid_ = "";

        dstid_ = "";

        packettype_ = 0;

        bodytype_ = 0;

        srccts_ = 0L;

        serverid_ = 0L;

        srcdeviceid_ = "";

        status_ = 0;

        cts_ = 0L;

        fromname_ = "";

        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xxim.codec.protobuf.PBMessage.internal_static_pbmessage_descriptor;
      }

      public com.xxim.codec.protobuf.PBMessage.pbmessage getDefaultInstanceForType() {
        return com.xxim.codec.protobuf.PBMessage.pbmessage.getDefaultInstance();
      }

      public com.xxim.codec.protobuf.PBMessage.pbmessage build() {
        com.xxim.codec.protobuf.PBMessage.pbmessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xxim.codec.protobuf.PBMessage.pbmessage buildPartial() {
        com.xxim.codec.protobuf.PBMessage.pbmessage result = new com.xxim.codec.protobuf.PBMessage.pbmessage(this);
        result.srcid_ = srcid_;
        result.dstid_ = dstid_;
        result.packettype_ = packettype_;
        result.bodytype_ = bodytype_;
        result.srccts_ = srccts_;
        result.serverid_ = serverid_;
        result.srcdeviceid_ = srcdeviceid_;
        result.status_ = status_;
        result.cts_ = cts_;
        result.fromname_ = fromname_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xxim.codec.protobuf.PBMessage.pbmessage) {
          return mergeFrom((com.xxim.codec.protobuf.PBMessage.pbmessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xxim.codec.protobuf.PBMessage.pbmessage other) {
        if (other == com.xxim.codec.protobuf.PBMessage.pbmessage.getDefaultInstance()) return this;
        if (!other.getSrcid().isEmpty()) {
          srcid_ = other.srcid_;
          onChanged();
        }
        if (!other.getDstid().isEmpty()) {
          dstid_ = other.dstid_;
          onChanged();
        }
        if (other.getPackettype() != 0) {
          setPackettype(other.getPackettype());
        }
        if (other.getBodytype() != 0) {
          setBodytype(other.getBodytype());
        }
        if (other.getSrccts() != 0L) {
          setSrccts(other.getSrccts());
        }
        if (other.getServerid() != 0L) {
          setServerid(other.getServerid());
        }
        if (!other.getSrcdeviceid().isEmpty()) {
          srcdeviceid_ = other.srcdeviceid_;
          onChanged();
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (other.getCts() != 0L) {
          setCts(other.getCts());
        }
        if (!other.getFromname().isEmpty()) {
          fromname_ = other.fromname_;
          onChanged();
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xxim.codec.protobuf.PBMessage.pbmessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xxim.codec.protobuf.PBMessage.pbmessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object srcid_ = "";
      /**
       * <code>string srcid = 1;</code>
       */
      public java.lang.String getSrcid() {
        java.lang.Object ref = srcid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          srcid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string srcid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSrcidBytes() {
        java.lang.Object ref = srcid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          srcid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string srcid = 1;</code>
       */
      public Builder setSrcid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        srcid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string srcid = 1;</code>
       */
      public Builder clearSrcid() {
        
        srcid_ = getDefaultInstance().getSrcid();
        onChanged();
        return this;
      }
      /**
       * <code>string srcid = 1;</code>
       */
      public Builder setSrcidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        srcid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dstid_ = "";
      /**
       * <code>string dstid = 2;</code>
       */
      public java.lang.String getDstid() {
        java.lang.Object ref = dstid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dstid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dstid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDstidBytes() {
        java.lang.Object ref = dstid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dstid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dstid = 2;</code>
       */
      public Builder setDstid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dstid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dstid = 2;</code>
       */
      public Builder clearDstid() {
        
        dstid_ = getDefaultInstance().getDstid();
        onChanged();
        return this;
      }
      /**
       * <code>string dstid = 2;</code>
       */
      public Builder setDstidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dstid_ = value;
        onChanged();
        return this;
      }

      private int packettype_ ;
      /**
       * <code>int32 packettype = 3;</code>
       */
      public int getPackettype() {
        return packettype_;
      }
      /**
       * <code>int32 packettype = 3;</code>
       */
      public Builder setPackettype(int value) {
        
        packettype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 packettype = 3;</code>
       */
      public Builder clearPackettype() {
        
        packettype_ = 0;
        onChanged();
        return this;
      }

      private int bodytype_ ;
      /**
       * <code>int32 bodytype = 4;</code>
       */
      public int getBodytype() {
        return bodytype_;
      }
      /**
       * <code>int32 bodytype = 4;</code>
       */
      public Builder setBodytype(int value) {
        
        bodytype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bodytype = 4;</code>
       */
      public Builder clearBodytype() {
        
        bodytype_ = 0;
        onChanged();
        return this;
      }

      private long srccts_ ;
      /**
       * <code>int64 srccts = 5;</code>
       */
      public long getSrccts() {
        return srccts_;
      }
      /**
       * <code>int64 srccts = 5;</code>
       */
      public Builder setSrccts(long value) {
        
        srccts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 srccts = 5;</code>
       */
      public Builder clearSrccts() {
        
        srccts_ = 0L;
        onChanged();
        return this;
      }

      private long serverid_ ;
      /**
       * <code>int64 serverid = 6;</code>
       */
      public long getServerid() {
        return serverid_;
      }
      /**
       * <code>int64 serverid = 6;</code>
       */
      public Builder setServerid(long value) {
        
        serverid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 serverid = 6;</code>
       */
      public Builder clearServerid() {
        
        serverid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object srcdeviceid_ = "";
      /**
       * <code>string srcdeviceid = 7;</code>
       */
      public java.lang.String getSrcdeviceid() {
        java.lang.Object ref = srcdeviceid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          srcdeviceid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string srcdeviceid = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSrcdeviceidBytes() {
        java.lang.Object ref = srcdeviceid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          srcdeviceid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string srcdeviceid = 7;</code>
       */
      public Builder setSrcdeviceid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        srcdeviceid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string srcdeviceid = 7;</code>
       */
      public Builder clearSrcdeviceid() {
        
        srcdeviceid_ = getDefaultInstance().getSrcdeviceid();
        onChanged();
        return this;
      }
      /**
       * <code>string srcdeviceid = 7;</code>
       */
      public Builder setSrcdeviceidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        srcdeviceid_ = value;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 8;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 8;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 8;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private long cts_ ;
      /**
       * <code>int64 cts = 9;</code>
       */
      public long getCts() {
        return cts_;
      }
      /**
       * <code>int64 cts = 9;</code>
       */
      public Builder setCts(long value) {
        
        cts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 cts = 9;</code>
       */
      public Builder clearCts() {
        
        cts_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object fromname_ = "";
      /**
       * <code>string fromname = 10;</code>
       */
      public java.lang.String getFromname() {
        java.lang.Object ref = fromname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fromname = 10;</code>
       */
      public com.google.protobuf.ByteString
          getFromnameBytes() {
        java.lang.Object ref = fromname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fromname = 10;</code>
       */
      public Builder setFromname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fromname = 10;</code>
       */
      public Builder clearFromname() {
        
        fromname_ = getDefaultInstance().getFromname();
        onChanged();
        return this;
      }
      /**
       * <code>string fromname = 10;</code>
       */
      public Builder setFromnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromname_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes body = 11;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>bytes body = 11;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes body = 11;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pbmessage)
    }

    // @@protoc_insertion_point(class_scope:pbmessage)
    private static final com.xxim.codec.protobuf.PBMessage.pbmessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xxim.codec.protobuf.PBMessage.pbmessage();
    }

    public static com.xxim.codec.protobuf.PBMessage.pbmessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<pbmessage>
        PARSER = new com.google.protobuf.AbstractParser<pbmessage>() {
      public pbmessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new pbmessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<pbmessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<pbmessage> getParserForType() {
      return PARSER;
    }

    public com.xxim.codec.protobuf.PBMessage.pbmessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbmessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbmessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017PBMessage.proto\"\303\001\n\tpbmessage\022\r\n\005srcid" +
      "\030\001 \001(\t\022\r\n\005dstid\030\002 \001(\t\022\022\n\npackettype\030\003 \001(" +
      "\005\022\020\n\010bodytype\030\004 \001(\005\022\016\n\006srccts\030\005 \001(\003\022\020\n\010s" +
      "erverid\030\006 \001(\003\022\023\n\013srcdeviceid\030\007 \001(\t\022\016\n\006st" +
      "atus\030\010 \001(\005\022\013\n\003cts\030\t \001(\003\022\020\n\010fromname\030\n \001(" +
      "\t\022\014\n\004body\030\013 \001(\014B$\n\027com.xxim.codec.protob" +
      "ufB\tPBMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pbmessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pbmessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbmessage_descriptor,
        new java.lang.String[] { "Srcid", "Dstid", "Packettype", "Bodytype", "Srccts", "Serverid", "Srcdeviceid", "Status", "Cts", "Fromname", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
